### ISSUE TITLE
SetState Switch wrong values on mistouch.

### ISSUE THREAD

**Issue by Umar-Khan-Yousafzai** [PramodJoshi/toggle_switch#26] opened 2021-03-30 13:24 UTC
Hi, I found this package to be very amazing but there is a strange issue that I just noticed. I saw that setState wasn't working at first in the switch. Luckily I found the example on this page. But there's is something I just noticed.

Let's say we have two values [User, Service Provider]

Now I have radiovalue variable set to 0.

      onToggle: (val){
                            print(radioval);
                            setState(() {
                              radioval = val;
                            });

                          },

The issue is that if a person in mistake presses the selected box more than once the value changes.

for an instance before touch the value for user was 0 and service provider was 1 and if user selected the user button more than once the value will change from 0 to 1 and service provider's value will become 0 and vice versa.

This is the issue. Is it possible to not change the value for selected index?

**Comment by Umar-Khan-Yousafzai** [comment] 2021-03-30 14:12
**In the original example of setState the author used the approach below**


class _MyScreenState extends State<MyScreen> {
  int initialIndex = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            margin: EdgeInsets.only(top: 30.0),
            child: ToggleSwitch(
                initialLabelIndex: initialIndex,
                labels: ['one', 'two'],
                onToggle: (index) {
                  print('switched index: $index');
                  setState(() {
                    initialIndex = index;
                  });
                })));
  }
}

now if a person pressed the label ''One" twice the index will change from 0 to 1 and then when he selects Label "two" the value will change to 0 and if a person mistakenly double clicks on "two" it will change the index again.  
 
 Sometimes both labels return the same value i.e 1 or 0 
-----------------------------------------------------------------------------------------------------------------

**Here is the updated Code.**

So, in case if anyone notices this issue further, I find a workaround without setState in the stateful widget, We can use provider to change value instead of assigning a separate variable for the toggle switch and then using the setState method.
```

 Padding(
                        padding: EdgeInsets.fromLTRB(12, 0, 0, 0),
                        child: ToggleSwitch(
                          minHeight: 44,
                          minWidth: 125,
                          fontFamily: 'GELIGHT',
                          fontSize: 13,
                          cornerRadius: 20.0,
                          activeFgColor: Colors.white,
                          inactiveBgColor: Colors.white,
                          inactiveFgColor: Colors.black,
                          labels: [
                            getTranslation(context, 'user'),
                            getTranslation(context, 'serviceprovider')
                          ],
                          activeBgColors: [Colors.blue, Colors.blue],
                          onToggle: (val){
                            print(val);
                              Provider.of<RegisterProvider>(context,listen: false).setUserorProvider(val);
                          },
                        ),
                      ),
```

For me, this approach is working fine. If anyone comes up with an easy approach that (doesn't include providers) please feel free to share.

**Again, Pramod thanks for this awesome widget.**

**Comment by Umar-Khan-Yousafzai** [comment] 2021-03-31 09:15
hi pramod. Thanks Well, this is very strange as it wasn't working as intended on my side, I have the same versions as you

**Comment by PramodJoshi** [comment] 2021-03-31 15:09
Interesting. I'll leave this issue open for now. Thanks.

**Comment by nikhilmufc7** [comment] 2021-06-07 08:42
Can confirm I can replicate this issue, 
My form has a textfield along with toggle switch so here are the steps to reproduce:
1. Select a new value using toggle switch
2. Tap on a textfield with switches focus and changes state. On changing state the toggle switch goes back to its initial value
if you are not able to reproduce I can help with a minimum reproducable example if needed

**Comment by PramodJoshi** [comment] 2021-06-07 14:21
@nikhilmufc7 Could you please post a complete runnable example?

**Comment by nikhilmufc7** [comment] 2021-06-08 18:35
@PramodJoshi I have added a example here where you can reproduce the issue https://gist.github.com/nikhilmufc7/a355ba0c031a7f7a4a32b6c2a28f8e65

Steps change the value of the toggle switch 
type something in the textfield and select ok or done using keyboard or change the focus

the toggle switch value goes back to default.
Let me know if you need anything else, cheers!

**Comment by PramodJoshi** [comment] 2021-06-08 21:57
@nikhilmufc7 Your example is different from what OP described. In your case, you're not saving your index. Please read/follow the example provided here - [setState inside onToggle](https://github.com/PramodJoshi/toggle_switch/issues/11#issuecomment-679277018)

Closing this.

**Closed by PramodJoshi** 2021-06-08 21:57 UTC
